# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Log into Artifactory & do the docker build
      - name: Login to jFrog
        run: 
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} dolpheus.jfrog.io
      
      # jFrog Login
      #- name: Login to jFrog
      #  uses: docker/login-action@v1 
      #  with:
      #    username: ${{ secrets.REGISTRY_USERNAME }}
      #    password: ${{ secrets.REGISTRY_PASSWORD }}
          
      # spare block
      - name: Docker build & Tag
        id: docker_build
        env:
          TAG: $(date +%s)
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          tags: docker-test-repo/team1-public-ip-printer:TAG
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
          
            

